---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       - hosts: localhost                                                                                                                                                                                                                             connection: local                                                                                                                                                                                                                            gather_facts: False                                                        
- hosts: localhost
  connection: local
  gather_facts: False
  become: True

  vars:
    key_name: eng84devops
    region: eu-west-1
    image: ami-038d7b856fe7557b3 
    id: "eng84_ula_3controller"
    sec_group: sg-0587ca02e184c3d9c #"{{ id }}-sec"
    subnet_id: subnet-0e9b6138ff1ce18f2

  tasks:

    - name: Facts
      block: 
 
      - name: Get instances facts
        ec2_instance_facts:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "{{ region }}"
        register: result

      tags: always  


    - name: Provisioning EC2 instances
      block:


      - name: APP instance
        ec2:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          key_name: "{{ key_name }}"
          id: eng84_ula_ansible_app
          vpc_subnet_id: "{{ public_subnet }}"
          group_id: "{{ public_sg }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
          assign_public_ip: yes
          instance_tags:
            Name: eng84_ula_ansible_app`   

      
      - name: DB instance
        ec2:
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          key_name: "{{ key_name }}"
          id: eng84_ula_ansible_db
          vpc_subnet_id: "{{ public_subnet }}"
          group_id: "{{ public_sg }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          wait: true
          count: 1
          assign_public_ip: yes
          instance_tags:
            Name: eng84_ula_ansible_db` 


        tags: ['never', 'create_ec2'] 
