---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       - hosts: localhost                                                                                                                                                                                                                             connection: local                                                                                                                                                                                                                            gather_facts: False                                                        
- hosts: db
  gather_facts: False
  become: True

  tasks:
  - name: Provision the db
  ansible.builtin.command: bash /home/ubuntu/provision_db.sh

 
